src/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.template.base import kwarg_re
from django.urls import path

from authentication.forms import LoginForm
from authentication.views import DashboardView

urlpatterns = [
    path('', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True,
        authentication_form=LoginForm
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard')
]

src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView, ProductView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductView.as_view(template_name='products/list.html', extra_context={
        'product': True
    }), name='list.product'),
]

src/authentication/models.py
from django.db import models

# Create your models here.

src/product/models.py
from django.db import models


# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    active = models.BooleanField(default=True)


class Product(models.Model):
    title = models.CharField(max_length=255,null=True, blank=True)
    sku = models.SlugField(max_length=255,null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

src/authentication/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    error_css_class = 'is-invalid'

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your username'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control form-control-user', 'placeholder': 'Enter your password'}
    ))

src/product/forms.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant, Product


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

class ProductForm(ModelForm):
    class Meta:
        model = Product        
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'sku': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
        }

src/authentication/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django import views
from django.utils.decorators import method_decorator


@method_decorator(login_required, name='dispatch')
class DashboardView(views.generic.TemplateView):
    template_name = 'dashboard.html'

src/product/views/product.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic import TemplateView

from product.models import Variant, Product, ProductVariant
from product.forms import  ProductForm
from product.filters import ProductFilter 


class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        return context

# class BaseProductView(generic.View):
#     form_class = ProductForm
#     model = Product
#     template_name = 'products/create.html'
#     success_url = 'product/products'


class ProductView(ListView):
    queryset = Product.objects.all()
    template_name = 'products/list.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['product'] = True
        context['variants'] = Variant.objects.all()
        context['filter'] = ProductFilter(self.request.GET, queryset=self.get_queryset())
        return context

    # def get_queryset(self):
    #     filter_string = {}
    #     print(self.request.GET)
    #     for key in self.request.GET:
    #         if self.request.GET.get(key):
    #             filter_string[key] = self.request.GET.get(key)
    #     return Product.objects.filter(**filter_string)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['variant'] = True
    #     context['request'] = ''
    #     if self.request.GET:
    #         context['request'] = self.request.GET['title__icontains']
    #     return context    

    






# class ProductCreateView(CreateProductView, CreateView):
#     pass
    

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/authentication/templates/login.html
{% extends 'website/base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user" method="post" novalidate>
                                        {% csrf_token %}
                                        <div class="form-group">
                                            {{ form.username }}
                                            <div class="text-danger list-unstyled">
                                                {{ form.username.errors }}
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            {{ form.password }}
                                            <div class="text-danger list-unstyled">
                                                {{ form.password.errors }}
                                            </div>
                                        </div>

                                        {#                                        {{ form.as_p }}#}
                                        <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>
                                    </form>
                                    <hr>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

src/pipenv/share/jupyter/nbconvert/templates/asciidoc/index.asciidoc.j2
{% extends 'display_priority.j2' %}


{% block input %}
{% if resources.global_content_filter.include_input_prompt %}
{% if cell.execution_count is defined -%}
    +*In[{{ cell.execution_count|replace(None, " ") }}]:*+
{% else %}
    +*In[]:*+
{%- endif -%}
{%- endif -%}
[source
{%- if 'magics_language' in cell.metadata  -%}
   , {{ cell.metadata.magics_language}}
{%- elif 'pygments_lexer' in nb.metadata.get('language_info', {}) -%}
   , {{ nb.metadata.language_info.pygments_lexer }}
{%- elif 'name' in nb.metadata.get('language_info', {}) -%}
   , {{ nb.metadata.language_info.name }}
{%- endif -%}]
----
{{ cell.source}}
----
{% endblock input %}

{% block output_group %}
{% if resources.global_content_filter.include_output_prompt %}
{% if cell.execution_count is defined -%}
    +*Out[{{ cell.execution_count|replace(None, " ") }}]:*+
{%- else -%}
    +*Out[]:*+
{%- endif -%}
{%- endif %}
----
{{- super() -}}
----
{% endblock output_group %}

{% block error %}
{{ super() }}
{% endblock error %}

{% block traceback_line %}
{{ line | indent | strip_ansi }}
{% endblock traceback_line %}

{%- block execute_result %}
{%- block data_priority scoped %}
{{- super() -}}
{%- endblock %}
{%- endblock execute_result %}

{% block stream %}
{{ output.text -}}
{% endblock stream %}

{% block data_svg %}
![svg]({{ output.metadata.filenames['image/svg+xml'] | path2url }})
{% endblock data_svg %}

{% block data_png %}
![png]({{ output.metadata.filenames['image/png'] | path2url }})
{% endblock data_png %}

{% block data_jpg %}
![jpeg]({{ output.metadata.filenames['image/jpeg'] | path2url }})
{% endblock data_jpg %}

{% block data_latex %}
{{ output.data['text/latex'] | convert_pandoc(from_format="latex", to_format="asciidoc")}}
{% endblock data_latex %}

{% block data_html scoped %}
{{ output.data['text/html'] | convert_pandoc(from_format='html', to_format='asciidoc')}}
{% endblock data_html %}

{% block data_markdown scoped %}
{{ output.data['text/markdown'] | markdown2asciidoc}}
{% endblock data_markdown %}

{% block data_text scoped %}
{{-output.data['text/plain']-}}
{% endblock data_text %}

{% block markdowncell scoped %}
{{ cell.source | markdown2asciidoc}}
{% endblock markdowncell %}

{% block unknowncell scoped %}
unknown type  {{ cell.type }}
{% endblock unknowncell %}

src/pipenv/share/jupyter/nbconvert/templates/base/celltags.j2
{%- macro celltags(cell) -%}
    {% if cell.metadata.tags | length > 0 -%}
        {% for tag in cell.metadata.tags -%}
            {{ ' celltag_' ~ tag -}}
        {%- endfor -%}
    {%- endif %}
{%- endmacro %}

src/pipenv/share/jupyter/nbconvert/templates/base/display_priority.j2
{%- extends 'base/null.j2' -%}

{#display data priority#}


{%- block data_priority scoped -%}
    {%- for type in output.data | filter_data_type -%}
        {%- if type == 'application/pdf' -%}
            {%- block data_pdf -%}
            {%- endblock -%}
        {%- elif type == 'image/svg+xml' -%}
            {%- block data_svg -%}
            {%- endblock -%}
        {%- elif type == 'image/png' -%}
            {%- block data_png -%}
            {%- endblock -%}
        {%- elif type == 'text/html' -%}
            {%- block data_html -%}
            {%- endblock -%}
        {%- elif type == 'text/markdown' -%}
            {%- block data_markdown -%}
            {%- endblock -%}
        {%- elif type == 'image/jpeg' -%}
            {%- block data_jpg -%}
            {%- endblock -%}
        {%- elif type == 'text/plain' -%}
            {%- block data_text -%}
            {%- endblock -%}
        {%- elif type == 'text/latex' -%}
            {%- block data_latex -%}
            {%- endblock -%}
        {%- elif type == 'application/javascript' -%}
            {%- block data_javascript -%}
            {%- endblock -%}
        {%- elif type == 'application/vnd.jupyter.widget-state+json' -%}
            {%- block data_widget_state -%}
            {%- endblock -%}
        {%- elif type == 'application/vnd.jupyter.widget-view+json' -%}
            {%- block data_widget_view -%}
            {%- endblock -%}
        {%- else -%}
            {%- block data_other -%}
            {%- endblock -%}
        {%- endif -%}
    {%- endfor -%}
{%- endblock data_priority -%}

src/pipenv/share/jupyter/nbconvert/templates/base/jupyter_widgets.html.j2
{%- macro jupyter_widgets(widgets_cdn_url, html_manager_semver_range) -%}

<script>
(function() {
  function addWidgetsRenderer() {
    var mimeElement = document.querySelector('script[type="application/vnd.jupyter.widget-view+json"]');
    var scriptElement = document.createElement('script');
    var widgetRendererSrc = '{{ widgets_cdn_url }}@jupyter-widgets/html-manager@{{ html_manager_semver_range }}/dist/embed-amd.js';
    var widgetState;

    // Fallback for older version:
    try {
      widgetState = mimeElement && JSON.parse(mimeElement.innerHTML);

      if (widgetState && (widgetState.version_major < 2 || !widgetState.version_major)) {
        widgetRendererSrc = '{{ widgets_cdn_url }}jupyter-js-widgets@*/dist/embed.js';
      }
    } catch(e) {}

    scriptElement.src = widgetRendererSrc;
    document.body.appendChild(scriptElement);
  }

  document.addEventListener('DOMContentLoaded', addWidgetsRenderer);
}());
</script>

{%- endmacro %}

src/pipenv/share/jupyter/nbconvert/templates/base/mathjax.html.j2
{%- macro mathjax(url="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-MML-AM_CHTML-full,Safe") -%}
    <!-- Load mathjax -->
    <script src="{{url}}"> </script>
    <!-- MathJax configuration -->
    <script type="text/x-mathjax-config">
    init_mathjax = function() {
        if (window.MathJax) {
        // MathJax loaded
            MathJax.Hub.Config({
                TeX: {
                    equationNumbers: {
                    autoNumber: "AMS",
                    useLabelIds: true
                    }
                },
                tex2jax: {
                    inlineMath: [ ['$','$'], ["\\(","\\)"] ],
                    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
                    processEscapes: true,
                    processEnvironments: true
                },
                displayAlign: 'center',
                CommonHTML: {
                    linebreaks: { 
                    automatic: true 
                    }
                },
                "HTML-CSS": {
                    linebreaks: { 
                    automatic: true 
                    }
                }
            });
        
            MathJax.Hub.Queue(["Typeset", MathJax.Hub]);
        }
    }
    init_mathjax();
    </script>
    <!-- End of mathjax configuration -->
{%- endmacro %}

src/pipenv/share/jupyter/nbconvert/templates/base/null.j2
{#

DO NOT USE THIS AS A BASE,
IF YOU ARE COPY AND PASTING THIS FILE
YOU ARE PROBABLY DOING THINGS INCORRECTLY.

Null template, does nothing except defining a basic structure
To layout the different blocks of a notebook.

Subtemplates can override blocks to define their custom representation.

If one of the block you do overwrite is not a leaf block, consider
calling super.

{%- block nonLeafBlock -%}
    #add stuff at beginning
    {{ super() }}
    #add stuff at end
{%- endblock nonLeafBlock -%}

consider calling super even if it is a leaf block, we might insert more blocks later.

#}
{%- block header -%}
{%- endblock header -%}
{%- block body -%}
    {%- block body_header -%}
    {%- endblock body_header -%}
    {%- block body_loop -%}
        {%- for cell in nb.cells -%}
            {%- block any_cell scoped -%}
                {%- if cell.cell_type == 'code'-%}
                    {%- if resources.global_content_filter.include_code -%}
                    {%- block codecell scoped -%}
                        {%- if resources.global_content_filter.include_input and not cell.get("transient",{}).get("remove_source", false) -%}
                            {%- block input_group -%}
                            {%- if resources.global_content_filter.include_input_prompt -%}
                                {%- block in_prompt -%}{%- endblock in_prompt -%}
                            {%- endif -%}
                                {%- block input -%}{%- endblock input -%}
                            {%- endblock input_group -%}
                        {%- endif -%}
                        {%- if cell.outputs and resources.global_content_filter.include_output -%}
                            {%- block output_group -%}
                                {%- if resources.global_content_filter.include_output_prompt -%}
                                    {%- block output_prompt -%}{%- endblock output_prompt -%}
                                {%- endif -%}
                                {%- block outputs scoped -%}
                                    {%- for output in cell.outputs -%}
                                        {%- block output scoped -%}
                                            {%- if output.output_type == 'execute_result' -%}
                                                {%- block execute_result scoped -%}{%- endblock execute_result -%}
                                            {%- elif output.output_type == 'stream' -%}
                                                {%- block stream scoped -%}
                                                    {%- if output.name == 'stdout' -%}
                                                        {%- block stream_stdout scoped -%}
                                                        {%- endblock stream_stdout -%}
                                                    {%- elif output.name == 'stderr' -%}
                                                        {%- block stream_stderr scoped -%}
                                                        {%- endblock stream_stderr -%}
                                                    {%- elif output.name == 'stdin' -%}
                                                        {%- block stream_stdin scoped -%}
                                                        {%- endblock stream_stdin -%}
                                                    {%- endif -%}
                                                {%- endblock stream -%}
                                            {%- elif output.output_type == 'display_data' -%}
                                                {%- block display_data scoped -%}
                                                    {%- block data_priority scoped -%}
                                                    {%- endblock data_priority -%}
                                                {%- endblock display_data -%}
                                            {%- elif output.output_type == 'error' -%}
                                                {%- block error scoped -%}
                                                {%- for line in output.traceback -%}
                                                    {%- block traceback_line scoped -%}{%- endblock traceback_line -%}
                                                {%- endfor -%}
                                                {%- endblock error -%}
                                            {%- endif -%}
                                        {%- endblock output -%}
                                    {%- endfor -%}
                                {%- endblock outputs -%}
                            {%- endblock output_group -%}
                        {%- endif -%}
                    {%- endblock codecell -%}
                    {%- endif -%}
                {%- elif cell.cell_type in ['markdown'] -%}
                    {%- if resources.global_content_filter.include_markdown and not cell.get("transient",{}).get("remove_source", false) -%}
                        {%- block markdowncell scoped-%} {%- endblock markdowncell -%}
                    {%- endif -%}
                {%- elif cell.cell_type in ['raw'] -%}
                    {%- if resources.global_content_filter.include_raw and not cell.get("transient",{}).get("remove_source", false) -%}
                        {%- block rawcell scoped -%}
                        {%- if cell.metadata.get('raw_mimetype', '').lower() in resources.get('raw_mimetypes', ['']) -%}
                        {{ cell.source }}
                        {%- endif -%}
                        {%- endblock rawcell -%}
                    {%- endif -%}
                {%- else -%}
                    {%- if resources.global_content_filter.include_unknown and not cell.get("transient",{}).get("remove_source", false) -%}
                        {%- block unknowncell scoped-%}
                        {%- endblock unknowncell -%}
                    {%- endif -%}
                {%- endif -%}
            {%- endblock any_cell -%}
        {%- endfor -%}
    {%- endblock body_loop -%}
    {%- block body_footer -%}
    {%- endblock body_footer -%}
{%- endblock body -%}

{%- block footer -%}
{%- endblock footer -%}

src/product/templates/variants/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Product Variant</h1>
        <a href="{% url 'product:variants' %}" class="float-right btn btn-primary">All Variant</a>
    </div>

    <div class="row justify-content-center">
        <form class="col-md-6" method="post" novalidate>
            {% csrf_token %}
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.title.label }}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.active }}
                        <label class="form-check-label" for="active">{{ form.active.label }}</label>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

src/product/templates/variants/list.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Product Variant</h1>
        <a href="{% url 'product:create.variant' %}" class="float-right btn btn-primary">+ New Variant</a>
    </div>

    <div class="card shadow mb-4">
        <form action="?" method="get" class="card-header py-3">
            <div class="form-row">
                <div class="col-md-3">
                    <input type="text" name="title__icontains" value="{{ request }}" placeholder="Serch"
                           class="form-control">
                </div>
                <div class="col-md-1">
                    <button class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for variant in variant_list %}
                        <tr>
                            <td>{{ variant.title }}</td>
                            <td>{{ variant.description }}</td>
                            <td>{{ variant.active }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    <a href="{% url 'product:update.variant' variant.id %}"
                                       class="btn btn-primary">Edit</a>
                                    <button type="button" class="btn btn-danger">Delete</button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/backend/particals/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Product</span>
        </a>
        <div id="collapsePages" class="collapse {% if product %} show {% endif %}" aria-labelledby="headingPages"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Product Option:</h6>
                <a class="collapse-item" href="{% url 'product:variants' %}">Variant</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Product:</h6>
                <a class="collapse-item" href="{% url 'product:create.product' %}">Create Product</a>
                <a class="collapse-item" href="{% url 'product:list.product' %}">All Product</a>
            </div>
        </div>
    </li>

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fas fa-fw fa-chart-area"></i>
            <span>Charts</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

src/templates/website/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Home
        {% endblock %}-Mediusware
    </title>
    <!-- Custom fonts for this template-->
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body class="bg-gradient-primary">
{% block content %}

{% endblock %}

</body>
</html>